### ISSUE TITLE
to com problema

### ISSUE THREAD

**Issue by andrekkn** [Pwniee/MLP_root#1]
ajuda

**Comment by Pwniee** [comment]
Olá Sra. Gabrielle , boa tarde!

Gostaríamos de primeiramente, pedir sinceras desculpas pelo transtorno causado, nós trabalhamos de forma firme na atenção de todos os casos e, na ocorrência de algum inconveniente, este trabalho é intensificado.

Esta reclamação será o seu contato direto na John John . Sinta-se a vontade em me retornar/questionar através de réplica, sem precisar ligar no SAC, pois seu atendimento é personalizado. 

Informamos que tentamos contato porém sem sucesso. 

Por favor, após resolução do problema, finalize esta reclamação com uma avaliação do meu atendimento, pois o Reclame Aqui utiliza esta para realizar melhorias e assim tornar a experiência de compra ainda melhor.

Estamos à disposição. 

Atenciosamente,
Equipe de Atendimento

**Comment by andrekkn** [comment]
valeu

**Comment by Pwniee** [comment]
Sr Erico



Obrigado por entrar em contato e nos relatar estes fatos.



Agradecemos pela crítica e opinião, pois nos ajudam a identificar o caminho para o aperfeiçoamento de nossos produtos e serviços.



Gostaríamos de nos desculpar pelo ocorrido em nossa churrascaria, já apuremos o ocorrido e medidas já foram tomadas para que isso não volte a acontecer, os mesmos já 



foram desligados da empresa.

**Comment by gldpittolzinho** [comment]
tambem tive esse problema

**Comment by gldpittolzinho** [comment]
como arruma

**Comment by gldpittolzinho** [comment]
venancio

**Comment by gldpittolzinho** [comment]
aires

**Comment by andrekkn** [comment]
duvida resolvida, valeu time!
